# Home

In this website, I will introduce the fundamentals of GitHub Actions and demonstrate how these workflows, along with tools like GitHub Copilot, can help automate different components of day-to-day modeling and analytics processes. The session will highlight practical, real-world examples of building simple pipelines that can run models, process data, and support routine reporting and analysis tasks. Attendees are expected to have a working GitHub account, as well as GitHub desktop (or knowledge how to use GitHub on their computers) up and running.

After the 30-min mark, we will turn into a more hands-on session where we will play with the template repository <https://github.com/gvegayon/gha-workshop-template> that I have created for this workshop. 

::: {.callout-important}
As with all things today, AI has contributed to the content of this project. The way I use AI is mostly via GitHub Copilot through code-completions and Agent mode in VS Code (Agentic AI). Some AI contributions may include commits via Pull Requests. Nonetheless, all the content has been reviewed and edited by me, and I take full responsibility for it. 
:::