name: Build and Deploy

on:
  pull_request:
    branches: [master, main]
  push:
    branches: [master, main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/${{ github.repository }}:latest

    steps:
    - uses: actions/checkout@v6

    - name: Render English version
      run: |
        cd site
        quarto render .

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v4
      with:
        path: _docs

  deploy:
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.merged == true }}
    runs-on: ubuntu-22.04

    # Add a dependency to the build job
    needs: build

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v5

